
name: Automated Tests for CI/CD

on:
  # triggers workflow for branch
  push:
    branches: [ automated-tests-code ]
  
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      # Installs dependencies
      - name: Install dependencies
        run: |
          pip3 install flask
          pip3 install dataset
          pip3 install pytest
          python3 setup.py
        
        name: Build Docker and run tests
        run: |
          docker build --tag python-docker . -f tests/Dockerfile
          docker images
          docker run -d -p 5000:5000 python-docker
          docker ps
          pytest