
name: Deploy to Production Server

on:
  push:
    branches: [ production ]
  
  # Allows manual trigger from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      #Checkout block
      - name: Checkout Current Version
        uses: actions/checkout@v3

      #SSH key for the runner machine to allow connection to the server
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PROD_SERVER_PEM }}
          name: ProdServer.pem
          known_hosts: ${{ secrets.PROD_KNOWN_HOSTS }}
          if_key_exists: replace
    
      #Runs the deployment scripts and verifications
      - name: Run a multi-line script
        run: |
          ls -la ~
          ls -la /home/runner/.ssh
          pushd deploy
          python3 --version
          pip3 --version
          pip3 install fabric
          python3 setup-ProdServer.py
          popd
          echo Done
