# This is a basic workflow to help you get started with Actions

name: Deploy to Prod Server

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ production ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PROD_SERVER_PEM }}
          name: ProdServer.pem
          known_hosts: ${{ secrets.PROD_KNOWN_HOSTS }}
    
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          ls -la ~
          ls -la /home/runner/.ssh
          pushd deploy
          python3 --version
          pip3 --version
          pip3 install fabric
          python3 setup-ProdServer.py
          popd
          echo Done
